//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;xhtml:div xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns="ddi:codebook:2_5" xmlns:dc="http://purl.org/dc/terms/" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:saxon="http://xml.apache.org/xslt" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;
 * 					&lt;xhtml:h1 class="element_title"&gt;Abstract Text Type&lt;/xhtml:h1&gt;
 * 					&lt;xhtml:div&gt;&lt;xhtml:h2 class="section_header"&gt;Description&lt;/xhtml:h2&gt;&lt;xhtml:div class="description"&gt;This type forms the basis for all textual elements. Textual elements may contain text or a mix of select elements. This type is abstract and is refined by more specific types which will limit the allowable elements and attributes. Any textual element will be a subset of this type and can be processed as such.&lt;/xhtml:div&gt;
 * 					&lt;/xhtml:div&gt;
 * 				&lt;/xhtml:div&gt;
 * </pre>
 *          
 *          
 * 
 * <p>Java class for abstractTextType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="abstractTextType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{ddi:codebook:2_5}GLOBALS"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "abstractTextType", namespace = "ddi:codebook:2_5", propOrder = {
    "content"
})
@XmlSeeAlso({
    QstnType.class,
    IntegerType.class,
    MaterialReferenceType.class,
    TableAndTextType.class,
    ConceptualTextType.class,
    OthRefsType.class,
    SimpleTextType.class,
    StringType.class,
    FormType.class,
    DateType.class
})
public abstract class AbstractTextType {

    @XmlValue
    protected String content;
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "xml-lang")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String xmlLang;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String lang;
    @XmlAttribute(name = "source")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String source;
    @XmlAttribute(name = "elementVersion")
    protected String elementVersion;
    @XmlAttribute(name = "elementVersionDate")
    protected String elementVersionDate;
    @XmlAttribute(name = "ddiLifecycleUrn")
    @XmlSchemaType(name = "anyURI")
    protected String ddiLifecycleUrn;
    @XmlAttribute(name = "ddiCodebookUrn")
    @XmlSchemaType(name = "anyURI")
    protected String ddiCodebookUrn;

    /**
     * 
     * 				
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;xhtml:div xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns="ddi:codebook:2_5" xmlns:dc="http://purl.org/dc/terms/" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:saxon="http://xml.apache.org/xslt" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;
     * 					&lt;xhtml:h1 class="element_title"&gt;Abstract Text Type&lt;/xhtml:h1&gt;
     * 					&lt;xhtml:div&gt;&lt;xhtml:h2 class="section_header"&gt;Description&lt;/xhtml:h2&gt;&lt;xhtml:div class="description"&gt;This type forms the basis for all textual elements. Textual elements may contain text or a mix of select elements. This type is abstract and is refined by more specific types which will limit the allowable elements and attributes. Any textual element will be a subset of this type and can be processed as such.&lt;/xhtml:div&gt;
     * 					&lt;/xhtml:div&gt;
     * 				&lt;/xhtml:div&gt;
     * </pre>
     *          
     *          
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the xmlLang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlLang() {
        return xmlLang;
    }

    /**
     * Sets the value of the xmlLang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlLang(String value) {
        this.xmlLang = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        if (source == null) {
            return "producer";
        } else {
            return source;
        }
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the elementVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementVersion() {
        return elementVersion;
    }

    /**
     * Sets the value of the elementVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementVersion(String value) {
        this.elementVersion = value;
    }

    /**
     * Gets the value of the elementVersionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementVersionDate() {
        return elementVersionDate;
    }

    /**
     * Sets the value of the elementVersionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementVersionDate(String value) {
        this.elementVersionDate = value;
    }

    /**
     * Gets the value of the ddiLifecycleUrn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDdiLifecycleUrn() {
        return ddiLifecycleUrn;
    }

    /**
     * Sets the value of the ddiLifecycleUrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDdiLifecycleUrn(String value) {
        this.ddiLifecycleUrn = value;
    }

    /**
     * Gets the value of the ddiCodebookUrn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDdiCodebookUrn() {
        return ddiCodebookUrn;
    }

    /**
     * Sets the value of the ddiCodebookUrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDdiCodebookUrn(String value) {
        this.ddiCodebookUrn = value;
    }

}
