//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anlyInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="anlyInfoType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:codebook:2_5}respRate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}EstSmpErr" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}dataAppr" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "anlyInfoType", namespace = "ddi:codebook:2_5", propOrder = {
    "respRate",
    "estSmpErr",
    "dataAppr"
})
public class AnlyInfoType
    extends BaseElementType
{

    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<SimpleTextType> respRate;
    @XmlElement(name = "EstSmpErr", namespace = "ddi:codebook:2_5")
    protected List<SimpleTextType> estSmpErr;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<DataApprType> dataAppr;

    /**
     * Gets the value of the respRate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the respRate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRespRate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleTextType }
     * 
     * 
     */
    public List<SimpleTextType> getRespRate() {
        if (respRate == null) {
            respRate = new ArrayList<SimpleTextType>();
        }
        return this.respRate;
    }

    /**
     * Gets the value of the estSmpErr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the estSmpErr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstSmpErr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleTextType }
     * 
     * 
     */
    public List<SimpleTextType> getEstSmpErr() {
        if (estSmpErr == null) {
            estSmpErr = new ArrayList<SimpleTextType>();
        }
        return this.estSmpErr;
    }

    /**
     * Gets the value of the dataAppr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataAppr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataAppr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataApprType }
     * 
     * 
     */
    public List<DataApprType> getDataAppr() {
        if (dataAppr == null) {
            dataAppr = new ArrayList<DataApprType>();
        }
        return this.dataAppr;
    }

}
