//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for catgryGrpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="catgryGrpType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:codebook:2_5}labl" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}catStat" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}txt" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="missing" default="N">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="Y"/>
 *             &lt;enumeration value="N"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="missType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="catgry" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute name="catGrp" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute name="levelno" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="levelnm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="compl" default="true">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="true"/>
 *             &lt;enumeration value="false"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="excls" default="true">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="true"/>
 *             &lt;enumeration value="false"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "catgryGrpType", namespace = "ddi:codebook:2_5", propOrder = {
    "labl",
    "catStat",
    "txt"
})
public class CatgryGrpType
    extends BaseElementType
{

    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<LablType> labl;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<CatStatType> catStat;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<TxtType> txt;
    @XmlAttribute(name = "missing")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String missing;
    @XmlAttribute(name = "missType")
    protected String missType;
    @XmlAttribute(name = "catgry")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> catgry;
    @XmlAttribute(name = "catGrp")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> catGrp;
    @XmlAttribute(name = "levelno")
    protected String levelno;
    @XmlAttribute(name = "levelnm")
    protected String levelnm;
    @XmlAttribute(name = "compl")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String compl;
    @XmlAttribute(name = "excls")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String excls;

    /**
     * Gets the value of the labl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LablType }
     * 
     * 
     */
    public List<LablType> getLabl() {
        if (labl == null) {
            labl = new ArrayList<LablType>();
        }
        return this.labl;
    }

    /**
     * Gets the value of the catStat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the catStat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCatStat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CatStatType }
     * 
     * 
     */
    public List<CatStatType> getCatStat() {
        if (catStat == null) {
            catStat = new ArrayList<CatStatType>();
        }
        return this.catStat;
    }

    /**
     * Gets the value of the txt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the txt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTxt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TxtType }
     * 
     * 
     */
    public List<TxtType> getTxt() {
        if (txt == null) {
            txt = new ArrayList<TxtType>();
        }
        return this.txt;
    }

    /**
     * Gets the value of the missing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMissing() {
        if (missing == null) {
            return "N";
        } else {
            return missing;
        }
    }

    /**
     * Sets the value of the missing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMissing(String value) {
        this.missing = value;
    }

    /**
     * Gets the value of the missType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMissType() {
        return missType;
    }

    /**
     * Sets the value of the missType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMissType(String value) {
        this.missType = value;
    }

    /**
     * Gets the value of the catgry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the catgry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCatgry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getCatgry() {
        if (catgry == null) {
            catgry = new ArrayList<Object>();
        }
        return this.catgry;
    }

    /**
     * Gets the value of the catGrp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the catGrp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCatGrp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getCatGrp() {
        if (catGrp == null) {
            catGrp = new ArrayList<Object>();
        }
        return this.catGrp;
    }

    /**
     * Gets the value of the levelno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevelno() {
        return levelno;
    }

    /**
     * Sets the value of the levelno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevelno(String value) {
        this.levelno = value;
    }

    /**
     * Gets the value of the levelnm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevelnm() {
        return levelnm;
    }

    /**
     * Sets the value of the levelnm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevelnm(String value) {
        this.levelnm = value;
    }

    /**
     * Gets the value of the compl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompl() {
        if (compl == null) {
            return "true";
        } else {
            return compl;
        }
    }

    /**
     * Sets the value of the compl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompl(String value) {
        this.compl = value;
    }

    /**
     * Gets the value of the excls property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcls() {
        if (excls == null) {
            return "true";
        } else {
            return excls;
        }
    }

    /**
     * Sets the value of the excls property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcls(String value) {
        this.excls = value;
    }

}
