//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for catLevelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="catLevelType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType">
 *       &lt;attribute name="levelnm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="geoMap" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "catLevelType", namespace = "ddi:codebook:2_5")
public class CatLevelType
    extends BaseElementType
{

    @XmlAttribute(name = "levelnm")
    protected String levelnm;
    @XmlAttribute(name = "geoMap")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> geoMap;

    /**
     * Gets the value of the levelnm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevelnm() {
        return levelnm;
    }

    /**
     * Sets the value of the levelnm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevelnm(String value) {
        this.levelnm = value;
    }

    /**
     * Gets the value of the geoMap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geoMap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeoMap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getGeoMap() {
        if (geoMap == null) {
            geoMap = new ArrayList<Object>();
        }
        return this.geoMap;
    }

}
