//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for controlledVocabUsedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="controlledVocabUsedType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:codebook:2_5}codeListID" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}codeListName" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}codeListAgencyName" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}codeListVersionID" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}codeListURN" minOccurs="0"/>
 *         &lt;element name="codeListSchemeURN" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}usage" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "controlledVocabUsedType", namespace = "ddi:codebook:2_5", propOrder = {
    "codeListID",
    "codeListName",
    "codeListAgencyName",
    "codeListVersionID",
    "codeListURN",
    "codeListSchemeURN",
    "usage"
})
public class ControlledVocabUsedType
    extends BaseElementType
{

    @XmlElement(namespace = "ddi:codebook:2_5")
    protected StringType codeListID;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected StringType codeListName;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected StringType codeListAgencyName;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected StringType codeListVersionID;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected StringType codeListURN;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected Object codeListSchemeURN;
    @XmlElement(namespace = "ddi:codebook:2_5", required = true)
    protected List<UsageType> usage;

    /**
     * Gets the value of the codeListID property.
     * 
     * @return
     *     possible object is
     *     {@link StringType }
     *     
     */
    public StringType getCodeListID() {
        return codeListID;
    }

    /**
     * Sets the value of the codeListID property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringType }
     *     
     */
    public void setCodeListID(StringType value) {
        this.codeListID = value;
    }

    /**
     * Gets the value of the codeListName property.
     * 
     * @return
     *     possible object is
     *     {@link StringType }
     *     
     */
    public StringType getCodeListName() {
        return codeListName;
    }

    /**
     * Sets the value of the codeListName property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringType }
     *     
     */
    public void setCodeListName(StringType value) {
        this.codeListName = value;
    }

    /**
     * Gets the value of the codeListAgencyName property.
     * 
     * @return
     *     possible object is
     *     {@link StringType }
     *     
     */
    public StringType getCodeListAgencyName() {
        return codeListAgencyName;
    }

    /**
     * Sets the value of the codeListAgencyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringType }
     *     
     */
    public void setCodeListAgencyName(StringType value) {
        this.codeListAgencyName = value;
    }

    /**
     * Gets the value of the codeListVersionID property.
     * 
     * @return
     *     possible object is
     *     {@link StringType }
     *     
     */
    public StringType getCodeListVersionID() {
        return codeListVersionID;
    }

    /**
     * Sets the value of the codeListVersionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringType }
     *     
     */
    public void setCodeListVersionID(StringType value) {
        this.codeListVersionID = value;
    }

    /**
     * Gets the value of the codeListURN property.
     * 
     * @return
     *     possible object is
     *     {@link StringType }
     *     
     */
    public StringType getCodeListURN() {
        return codeListURN;
    }

    /**
     * Sets the value of the codeListURN property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringType }
     *     
     */
    public void setCodeListURN(StringType value) {
        this.codeListURN = value;
    }

    /**
     * Gets the value of the codeListSchemeURN property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCodeListSchemeURN() {
        return codeListSchemeURN;
    }

    /**
     * Sets the value of the codeListSchemeURN property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCodeListSchemeURN(Object value) {
        this.codeListSchemeURN = value;
    }

    /**
     * Gets the value of the usage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UsageType }
     * 
     * 
     */
    public List<UsageType> getUsage() {
        if (usage == null) {
            usage = new ArrayList<UsageType>();
        }
        return this.usage;
    }

}
