//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CubeCoordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CubeCoordType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType">
 *       &lt;attribute name="coordNo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="coordVal" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="coordValRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CubeCoordType", namespace = "ddi:codebook:2_5")
public class CubeCoordType
    extends BaseElementType
{

    @XmlAttribute(name = "coordNo")
    protected String coordNo;
    @XmlAttribute(name = "coordVal")
    protected String coordVal;
    @XmlAttribute(name = "coordValRef")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object coordValRef;

    /**
     * Gets the value of the coordNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoordNo() {
        return coordNo;
    }

    /**
     * Sets the value of the coordNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoordNo(String value) {
        this.coordNo = value;
    }

    /**
     * Gets the value of the coordVal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoordVal() {
        return coordVal;
    }

    /**
     * Sets the value of the coordVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoordVal(String value) {
        this.coordVal = value;
    }

    /**
     * Gets the value of the coordValRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCoordValRef() {
        return coordValRef;
    }

    /**
     * Sets the value of the coordValRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCoordValRef(Object value) {
        this.coordValRef = value;
    }

}
