//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dataDscrType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataDscrType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:codebook:2_5}varGrp" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}nCubeGrp" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}var" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}nCube" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}notes" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataDscrType", namespace = "ddi:codebook:2_5", propOrder = {
    "varGrp",
    "nCubeGrp",
    "var",
    "nCube",
    "notes"
})
public class DataDscrType
    extends BaseElementType
{

    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<VarGrpType> varGrp;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<NCubeGrpType> nCubeGrp;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected ArrayList<VarType> var;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<NCubeType> nCube;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<NotesType> notes;

    /**
     * Gets the value of the varGrp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the varGrp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVarGrp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VarGrpType }
     * 
     * 
     */
    public List<VarGrpType> getVarGrp() {
        if (varGrp == null) {
            varGrp = new ArrayList<VarGrpType>();
        }
        return this.varGrp;
    }

    /**
     * Gets the value of the nCubeGrp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nCubeGrp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNCubeGrp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NCubeGrpType }
     * 
     * 
     */
    public List<NCubeGrpType> getNCubeGrp() {
        if (nCubeGrp == null) {
            nCubeGrp = new ArrayList<NCubeGrpType>();
        }
        return this.nCubeGrp;
    }

    /**
     * Gets the value of the var property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the var property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVar().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VarType }
     * 
     * 
     */
    public ArrayList<VarType> getVar() {
        if (var == null) {
            var = new ArrayList<VarType>();
        }
        return this.var;
    }

    public void setVar(ArrayList<VarType> var) {
		this.var = var;
	}

	/**
     * Gets the value of the nCube property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nCube property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNCube().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NCubeType }
     * 
     * 
     */
    public List<NCubeType> getNCube() {
        if (nCube == null) {
            nCube = new ArrayList<NCubeType>();
        }
        return this.nCube;
    }

    /**
     * Gets the value of the notes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NotesType }
     * 
     * 
     */
    public List<NotesType> getNotes() {
        if (notes == null) {
            notes = new ArrayList<NotesType>();
        }
        return this.notes;
    }

}
