//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dataItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataItemType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:codebook:2_5}CubeCoord" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}physLoc" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="varRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="nCubeRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataItemType", namespace = "ddi:codebook:2_5", propOrder = {
    "cubeCoord",
    "physLoc"
})
public class DataItemType
    extends BaseElementType
{

    @XmlElement(name = "CubeCoord", namespace = "ddi:codebook:2_5")
    protected List<CubeCoordType> cubeCoord;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<PhysLocType> physLoc;
    @XmlAttribute(name = "varRef")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object varRef;
    @XmlAttribute(name = "nCubeRef")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object nCubeRef;

    /**
     * Gets the value of the cubeCoord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cubeCoord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCubeCoord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CubeCoordType }
     * 
     * 
     */
    public List<CubeCoordType> getCubeCoord() {
        if (cubeCoord == null) {
            cubeCoord = new ArrayList<CubeCoordType>();
        }
        return this.cubeCoord;
    }

    /**
     * Gets the value of the physLoc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the physLoc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhysLoc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhysLocType }
     * 
     * 
     */
    public List<PhysLocType> getPhysLoc() {
        if (physLoc == null) {
            physLoc = new ArrayList<PhysLocType>();
        }
        return this.physLoc;
    }

    /**
     * Gets the value of the varRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getVarRef() {
        return varRef;
    }

    /**
     * Sets the value of the varRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setVarRef(Object value) {
        this.varRef = value;
    }

    /**
     * Gets the value of the nCubeRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNCubeRef() {
        return nCubeRef;
    }

    /**
     * Sets the value of the nCubeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNCubeRef(Object value) {
        this.nCubeRef = value;
    }

}
