//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dimensnsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dimensnsType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:codebook:2_5}caseQnty" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}varQnty" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}logRecL" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}recPrCas" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}recNumTot" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dimensnsType", namespace = "ddi:codebook:2_5", propOrder = {
    "caseQnty",
    "varQnty",
    "logRecL",
    "recPrCas",
    "recNumTot"
})
public class DimensnsType
    extends BaseElementType
{

    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<SimpleTextType> caseQnty;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<SimpleTextType> varQnty;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<SimpleTextType> logRecL;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<SimpleTextType> recPrCas;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<SimpleTextType> recNumTot;

    /**
     * Gets the value of the caseQnty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the caseQnty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCaseQnty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleTextType }
     * 
     * 
     */
    public List<SimpleTextType> getCaseQnty() {
        if (caseQnty == null) {
            caseQnty = new ArrayList<SimpleTextType>();
        }
        return this.caseQnty;
    }

    /**
     * Gets the value of the varQnty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the varQnty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVarQnty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleTextType }
     * 
     * 
     */
    public List<SimpleTextType> getVarQnty() {
        if (varQnty == null) {
            varQnty = new ArrayList<SimpleTextType>();
        }
        return this.varQnty;
    }

    /**
     * Gets the value of the logRecL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the logRecL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLogRecL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleTextType }
     * 
     * 
     */
    public List<SimpleTextType> getLogRecL() {
        if (logRecL == null) {
            logRecL = new ArrayList<SimpleTextType>();
        }
        return this.logRecL;
    }

    /**
     * Gets the value of the recPrCas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recPrCas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecPrCas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleTextType }
     * 
     * 
     */
    public List<SimpleTextType> getRecPrCas() {
        if (recPrCas == null) {
            recPrCas = new ArrayList<SimpleTextType>();
        }
        return this.recPrCas;
    }

    /**
     * Gets the value of the recNumTot property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recNumTot property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecNumTot().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleTextType }
     * 
     * 
     */
    public List<SimpleTextType> getRecNumTot() {
        if (recNumTot == null) {
            recNumTot = new ArrayList<SimpleTextType>();
        }
        return this.recNumTot;
    }

}
