//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for distStmtType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="distStmtType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:codebook:2_5}distrbtr" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}contact" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}depositr" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}depDate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}distDate" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "distStmtType", namespace = "ddi:codebook:2_5", propOrder = {
    "distrbtr",
    "contact",
    "depositr",
    "depDate",
    "distDate"
})
public class DistStmtType
    extends BaseElementType
{

    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<DistrbtrType> distrbtr;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<ContactType> contact;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<DepositrType> depositr;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<SimpleTextAndDateType> depDate;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<SimpleTextAndDateType> distDate;

    /**
     * Gets the value of the distrbtr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the distrbtr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDistrbtr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DistrbtrType }
     * 
     * 
     */
    public List<DistrbtrType> getDistrbtr() {
        if (distrbtr == null) {
            distrbtr = new ArrayList<DistrbtrType>();
        }
        return this.distrbtr;
    }

    /**
     * Gets the value of the contact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactType }
     * 
     * 
     */
    public List<ContactType> getContact() {
        if (contact == null) {
            contact = new ArrayList<ContactType>();
        }
        return this.contact;
    }

    /**
     * Gets the value of the depositr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the depositr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDepositr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DepositrType }
     * 
     * 
     */
    public List<DepositrType> getDepositr() {
        if (depositr == null) {
            depositr = new ArrayList<DepositrType>();
        }
        return this.depositr;
    }

    /**
     * Gets the value of the depDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the depDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDepDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleTextAndDateType }
     * 
     * 
     */
    public List<SimpleTextAndDateType> getDepDate() {
        if (depDate == null) {
            depDate = new ArrayList<SimpleTextAndDateType>();
        }
        return this.depDate;
    }

    /**
     * Gets the value of the distDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the distDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDistDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleTextAndDateType }
     * 
     * 
     */
    public List<SimpleTextAndDateType> getDistDate() {
        if (distDate == null) {
            distDate = new ArrayList<SimpleTextAndDateType>();
        }
        return this.distDate;
    }

}
