//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for docSrcType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="docSrcType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:codebook:2_5}titlStmt"/>
 *         &lt;element ref="{ddi:codebook:2_5}rspStmt" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}prodStmt" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}distStmt" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}serStmt" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}verStmt" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}biblCit" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}holdings" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}notes" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="MARCURI" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "docSrcType", namespace = "ddi:codebook:2_5", propOrder = {
    "titlStmt",
    "rspStmt",
    "prodStmt",
    "distStmt",
    "serStmt",
    "verStmt",
    "biblCit",
    "holdings",
    "notes"
})
public class DocSrcType
    extends BaseElementType
{

    @XmlElement(namespace = "ddi:codebook:2_5", required = true)
    protected TitlStmtType titlStmt;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected RspStmtType rspStmt;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected ProdStmtType prodStmt;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected DistStmtType distStmt;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<SerStmtType> serStmt;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<VerStmtType> verStmt;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<BiblCitType> biblCit;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<HoldingsType> holdings;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<NotesType> notes;
    @XmlAttribute(name = "MARCURI")
    protected String marcuri;

    /**
     * Gets the value of the titlStmt property.
     * 
     * @return
     *     possible object is
     *     {@link TitlStmtType }
     *     
     */
    public TitlStmtType getTitlStmt() {
        return titlStmt;
    }

    /**
     * Sets the value of the titlStmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitlStmtType }
     *     
     */
    public void setTitlStmt(TitlStmtType value) {
        this.titlStmt = value;
    }

    /**
     * Gets the value of the rspStmt property.
     * 
     * @return
     *     possible object is
     *     {@link RspStmtType }
     *     
     */
    public RspStmtType getRspStmt() {
        return rspStmt;
    }

    /**
     * Sets the value of the rspStmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link RspStmtType }
     *     
     */
    public void setRspStmt(RspStmtType value) {
        this.rspStmt = value;
    }

    /**
     * Gets the value of the prodStmt property.
     * 
     * @return
     *     possible object is
     *     {@link ProdStmtType }
     *     
     */
    public ProdStmtType getProdStmt() {
        return prodStmt;
    }

    /**
     * Sets the value of the prodStmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProdStmtType }
     *     
     */
    public void setProdStmt(ProdStmtType value) {
        this.prodStmt = value;
    }

    /**
     * Gets the value of the distStmt property.
     * 
     * @return
     *     possible object is
     *     {@link DistStmtType }
     *     
     */
    public DistStmtType getDistStmt() {
        return distStmt;
    }

    /**
     * Sets the value of the distStmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistStmtType }
     *     
     */
    public void setDistStmt(DistStmtType value) {
        this.distStmt = value;
    }

    /**
     * Gets the value of the serStmt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serStmt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSerStmt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SerStmtType }
     * 
     * 
     */
    public List<SerStmtType> getSerStmt() {
        if (serStmt == null) {
            serStmt = new ArrayList<SerStmtType>();
        }
        return this.serStmt;
    }

    /**
     * Gets the value of the verStmt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the verStmt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVerStmt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VerStmtType }
     * 
     * 
     */
    public List<VerStmtType> getVerStmt() {
        if (verStmt == null) {
            verStmt = new ArrayList<VerStmtType>();
        }
        return this.verStmt;
    }

    /**
     * Gets the value of the biblCit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the biblCit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBiblCit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BiblCitType }
     * 
     * 
     */
    public List<BiblCitType> getBiblCit() {
        if (biblCit == null) {
            biblCit = new ArrayList<BiblCitType>();
        }
        return this.biblCit;
    }

    /**
     * Gets the value of the holdings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the holdings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHoldings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HoldingsType }
     * 
     * 
     */
    public List<HoldingsType> getHoldings() {
        if (holdings == null) {
            holdings = new ArrayList<HoldingsType>();
        }
        return this.holdings;
    }

    /**
     * Gets the value of the notes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NotesType }
     * 
     * 
     */
    public List<NotesType> getNotes() {
        if (notes == null) {
            notes = new ArrayList<NotesType>();
        }
        return this.notes;
    }

    /**
     * Gets the value of the marcuri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMARCURI() {
        return marcuri;
    }

    /**
     * Sets the value of the marcuri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMARCURI(String value) {
        this.marcuri = value;
    }

}
