//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for measureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="measureType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType">
 *       &lt;attribute name="varRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="aggrMeth">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="sum"/>
 *             &lt;enumeration value="average"/>
 *             &lt;enumeration value="count"/>
 *             &lt;enumeration value="mode"/>
 *             &lt;enumeration value="median"/>
 *             &lt;enumeration value="maximum"/>
 *             &lt;enumeration value="minimum"/>
 *             &lt;enumeration value="percent"/>
 *             &lt;enumeration value="other"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="otherAggrMeth" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="measUnit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="scale" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="origin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="additivity">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="stock"/>
 *             &lt;enumeration value="flow"/>
 *             &lt;enumeration value="non-additive"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "measureType", namespace = "ddi:codebook:2_5")
public class MeasureType
    extends BaseElementType
{

    @XmlAttribute(name = "varRef")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object varRef;
    @XmlAttribute(name = "aggrMeth")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String aggrMeth;
    @XmlAttribute(name = "otherAggrMeth")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String otherAggrMeth;
    @XmlAttribute(name = "measUnit")
    protected String measUnit;
    @XmlAttribute(name = "scale")
    protected String scale;
    @XmlAttribute(name = "origin")
    protected String origin;
    @XmlAttribute(name = "additivity")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String additivity;

    /**
     * Gets the value of the varRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getVarRef() {
        return varRef;
    }

    /**
     * Sets the value of the varRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setVarRef(Object value) {
        this.varRef = value;
    }

    /**
     * Gets the value of the aggrMeth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAggrMeth() {
        return aggrMeth;
    }

    /**
     * Sets the value of the aggrMeth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAggrMeth(String value) {
        this.aggrMeth = value;
    }

    /**
     * Gets the value of the otherAggrMeth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherAggrMeth() {
        return otherAggrMeth;
    }

    /**
     * Sets the value of the otherAggrMeth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherAggrMeth(String value) {
        this.otherAggrMeth = value;
    }

    /**
     * Gets the value of the measUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasUnit() {
        return measUnit;
    }

    /**
     * Sets the value of the measUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasUnit(String value) {
        this.measUnit = value;
    }

    /**
     * Gets the value of the scale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScale() {
        return scale;
    }

    /**
     * Sets the value of the scale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScale(String value) {
        this.scale = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

    /**
     * Gets the value of the additivity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditivity() {
        return additivity;
    }

    /**
     * Sets the value of the additivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditivity(String value) {
        this.additivity = value;
    }

}
