//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for methodType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="methodType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:codebook:2_5}dataColl" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}notes" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}anlyInfo" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}stdyClas" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}dataProcessing" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}codingInstructions" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "methodType", namespace = "ddi:codebook:2_5", propOrder = {
    "dataColl",
    "notes",
    "anlyInfo",
    "stdyClas",
    "dataProcessing",
    "codingInstructions"
})
public class MethodType
    extends BaseElementType
{

    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<DataCollType> dataColl;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<NotesType> notes;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected AnlyInfoType anlyInfo;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<StdyClasType> stdyClas;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<DataProcessingType> dataProcessing;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<CodingInstructionsType> codingInstructions;

    /**
     * Gets the value of the dataColl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataColl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataColl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataCollType }
     * 
     * 
     */
    public List<DataCollType> getDataColl() {
        if (dataColl == null) {
            dataColl = new ArrayList<DataCollType>();
        }
        return this.dataColl;
    }

    /**
     * Gets the value of the notes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NotesType }
     * 
     * 
     */
    public List<NotesType> getNotes() {
        if (notes == null) {
            notes = new ArrayList<NotesType>();
        }
        return this.notes;
    }

    /**
     * Gets the value of the anlyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AnlyInfoType }
     *     
     */
    public AnlyInfoType getAnlyInfo() {
        return anlyInfo;
    }

    /**
     * Sets the value of the anlyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnlyInfoType }
     *     
     */
    public void setAnlyInfo(AnlyInfoType value) {
        this.anlyInfo = value;
    }

    /**
     * Gets the value of the stdyClas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stdyClas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStdyClas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StdyClasType }
     * 
     * 
     */
    public List<StdyClasType> getStdyClas() {
        if (stdyClas == null) {
            stdyClas = new ArrayList<StdyClasType>();
        }
        return this.stdyClas;
    }

    /**
     * Gets the value of the dataProcessing property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataProcessing property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataProcessing().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataProcessingType }
     * 
     * 
     */
    public List<DataProcessingType> getDataProcessing() {
        if (dataProcessing == null) {
            dataProcessing = new ArrayList<DataProcessingType>();
        }
        return this.dataProcessing;
    }

    /**
     * Gets the value of the codingInstructions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the codingInstructions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCodingInstructions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodingInstructionsType }
     * 
     * 
     */
    public List<CodingInstructionsType> getCodingInstructions() {
        if (codingInstructions == null) {
            codingInstructions = new ArrayList<CodingInstructionsType>();
        }
        return this.codingInstructions;
    }

}
