//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for othrStdyMatType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="othrStdyMatType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:codebook:2_5}relMat" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}relStdy" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}relPubl" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}othRefs" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "othrStdyMatType", namespace = "ddi:codebook:2_5", propOrder = {
    "relMat",
    "relStdy",
    "relPubl",
    "othRefs"
})
public class OthrStdyMatType
    extends BaseElementType
{

    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<RelMatType> relMat;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<MaterialReferenceType> relStdy;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<MaterialReferenceType> relPubl;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<OthRefsType> othRefs;

    /**
     * Gets the value of the relMat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relMat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelMat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelMatType }
     * 
     * 
     */
    public List<RelMatType> getRelMat() {
        if (relMat == null) {
            relMat = new ArrayList<RelMatType>();
        }
        return this.relMat;
    }

    /**
     * Gets the value of the relStdy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relStdy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelStdy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MaterialReferenceType }
     * 
     * 
     */
    public List<MaterialReferenceType> getRelStdy() {
        if (relStdy == null) {
            relStdy = new ArrayList<MaterialReferenceType>();
        }
        return this.relStdy;
    }

    /**
     * Gets the value of the relPubl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relPubl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelPubl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MaterialReferenceType }
     * 
     * 
     */
    public List<MaterialReferenceType> getRelPubl() {
        if (relPubl == null) {
            relPubl = new ArrayList<MaterialReferenceType>();
        }
        return this.relPubl;
    }

    /**
     * Gets the value of the othRefs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the othRefs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOthRefs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OthRefsType }
     * 
     * 
     */
    public List<OthRefsType> getOthRefs() {
        if (othRefs == null) {
            othRefs = new ArrayList<OthRefsType>();
        }
        return this.othRefs;
    }

}
