//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pointType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pointType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:codebook:2_5}gringLat"/>
 *         &lt;element ref="{ddi:codebook:2_5}gringLon"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pointType", namespace = "ddi:codebook:2_5", propOrder = {
    "gringLat",
    "gringLon"
})
public class PointType
    extends BaseElementType
{

    @XmlElement(namespace = "ddi:codebook:2_5", required = true)
    protected PhraseType gringLat;
    @XmlElement(namespace = "ddi:codebook:2_5", required = true)
    protected PhraseType gringLon;

    /**
     * Gets the value of the gringLat property.
     * 
     * @return
     *     possible object is
     *     {@link PhraseType }
     *     
     */
    public PhraseType getGringLat() {
        return gringLat;
    }

    /**
     * Sets the value of the gringLat property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhraseType }
     *     
     */
    public void setGringLat(PhraseType value) {
        this.gringLat = value;
    }

    /**
     * Gets the value of the gringLon property.
     * 
     * @return
     *     possible object is
     *     {@link PhraseType }
     *     
     */
    public PhraseType getGringLon() {
        return gringLon;
    }

    /**
     * Sets the value of the gringLon property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhraseType }
     *     
     */
    public void setGringLon(PhraseType value) {
        this.gringLon = value;
    }

}
