//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for recDimnsnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="recDimnsnType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:codebook:2_5}varQnty" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}caseQnty" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}logRecL" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recDimnsnType", namespace = "ddi:codebook:2_5", propOrder = {
    "varQnty",
    "caseQnty",
    "logRecL"
})
public class RecDimnsnType
    extends BaseElementType
{

    @XmlElement(namespace = "ddi:codebook:2_5")
    protected SimpleTextType varQnty;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected SimpleTextType caseQnty;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected SimpleTextType logRecL;
    @XmlAttribute(name = "level")
    protected String level;

    /**
     * Gets the value of the varQnty property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTextType }
     *     
     */
    public SimpleTextType getVarQnty() {
        return varQnty;
    }

    /**
     * Sets the value of the varQnty property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTextType }
     *     
     */
    public void setVarQnty(SimpleTextType value) {
        this.varQnty = value;
    }

    /**
     * Gets the value of the caseQnty property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTextType }
     *     
     */
    public SimpleTextType getCaseQnty() {
        return caseQnty;
    }

    /**
     * Sets the value of the caseQnty property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTextType }
     *     
     */
    public void setCaseQnty(SimpleTextType value) {
        this.caseQnty = value;
    }

    /**
     * Gets the value of the logRecL property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTextType }
     *     
     */
    public SimpleTextType getLogRecL() {
        return logRecL;
    }

    /**
     * Sets the value of the logRecL property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTextType }
     *     
     */
    public void setLogRecL(SimpleTextType value) {
        this.logRecL = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel(String value) {
        this.level = value;
    }

}
