//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for recGrpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="recGrpType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:codebook:2_5}labl" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}recDimnsn" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="recGrp" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute name="rectype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="keyvar" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute name="rtypeloc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rtypewidth" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
 *       &lt;attribute name="rtypevtype" default="numeric">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="numeric"/>
 *             &lt;enumeration value="character"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="recidvar" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recGrpType", namespace = "ddi:codebook:2_5", propOrder = {
    "labl",
    "recDimnsn"
})
public class RecGrpType
    extends BaseElementType
{

    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<LablType> labl;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected RecDimnsnType recDimnsn;
    @XmlAttribute(name = "recGrp")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> recGrp;
    @XmlAttribute(name = "rectype")
    protected String rectype;
    @XmlAttribute(name = "keyvar")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> keyvar;
    @XmlAttribute(name = "rtypeloc")
    protected String rtypeloc;
    @XmlAttribute(name = "rtypewidth")
    protected String rtypewidth;
    @XmlAttribute(name = "rtypevtype")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rtypevtype;
    @XmlAttribute(name = "recidvar")
    protected String recidvar;

    /**
     * Gets the value of the labl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LablType }
     * 
     * 
     */
    public List<LablType> getLabl() {
        if (labl == null) {
            labl = new ArrayList<LablType>();
        }
        return this.labl;
    }

    /**
     * Gets the value of the recDimnsn property.
     * 
     * @return
     *     possible object is
     *     {@link RecDimnsnType }
     *     
     */
    public RecDimnsnType getRecDimnsn() {
        return recDimnsn;
    }

    /**
     * Sets the value of the recDimnsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecDimnsnType }
     *     
     */
    public void setRecDimnsn(RecDimnsnType value) {
        this.recDimnsn = value;
    }

    /**
     * Gets the value of the recGrp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recGrp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecGrp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getRecGrp() {
        if (recGrp == null) {
            recGrp = new ArrayList<Object>();
        }
        return this.recGrp;
    }

    /**
     * Gets the value of the rectype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRectype() {
        return rectype;
    }

    /**
     * Sets the value of the rectype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRectype(String value) {
        this.rectype = value;
    }

    /**
     * Gets the value of the keyvar property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyvar property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeyvar().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getKeyvar() {
        if (keyvar == null) {
            keyvar = new ArrayList<Object>();
        }
        return this.keyvar;
    }

    /**
     * Gets the value of the rtypeloc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtypeloc() {
        return rtypeloc;
    }

    /**
     * Sets the value of the rtypeloc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtypeloc(String value) {
        this.rtypeloc = value;
    }

    /**
     * Gets the value of the rtypewidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtypewidth() {
        if (rtypewidth == null) {
            return "1";
        } else {
            return rtypewidth;
        }
    }

    /**
     * Sets the value of the rtypewidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtypewidth(String value) {
        this.rtypewidth = value;
    }

    /**
     * Gets the value of the rtypevtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtypevtype() {
        if (rtypevtype == null) {
            return "numeric";
        } else {
            return rtypevtype;
        }
    }

    /**
     * Sets the value of the rtypevtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtypevtype(String value) {
        this.rtypevtype = value;
    }

    /**
     * Gets the value of the recidvar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecidvar() {
        return recidvar;
    }

    /**
     * Sets the value of the recidvar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecidvar(String value) {
        this.recidvar = value;
    }

}
