//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rspStmtType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rspStmtType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:codebook:2_5}AuthEnty" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}othId" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rspStmtType", namespace = "ddi:codebook:2_5", propOrder = {
    "authEnty",
    "othId"
})
public class RspStmtType
    extends BaseElementType
{

    @XmlElement(name = "AuthEnty", namespace = "ddi:codebook:2_5")
    protected List<AuthEntyType> authEnty;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<OthIdType> othId;

    /**
     * Gets the value of the authEnty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authEnty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthEnty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthEntyType }
     * 
     * 
     */
    public List<AuthEntyType> getAuthEnty() {
        if (authEnty == null) {
            authEnty = new ArrayList<AuthEntyType>();
        }
        return this.authEnty;
    }

    /**
     * Gets the value of the othId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the othId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOthId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OthIdType }
     * 
     * 
     */
    public List<OthIdType> getOthId() {
        if (othId == null) {
            othId = new ArrayList<OthIdType>();
        }
        return this.othId;
    }

}
