//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stdyInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stdyInfoType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:codebook:2_5}studyBudget" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}subject" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}abstract" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}sumDscr" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}qualityStatement" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}notes" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}exPostEvaluation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stdyInfoType", namespace = "ddi:codebook:2_5", propOrder = {
    "studyBudget",
    "subject",
    "_abstract",
    "sumDscr",
    "qualityStatement",
    "notes",
    "exPostEvaluation"
})
public class StdyInfoType
    extends BaseElementType
{

    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<SimpleTextType> studyBudget;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<SubjectType> subject;
    @XmlElement(name = "abstract", namespace = "ddi:codebook:2_5")
    protected List<AbstractType> _abstract;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<SumDscrType> sumDscr;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected QualityStatementType qualityStatement;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<NotesType> notes;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<ExPostEvaluationType> exPostEvaluation;

    /**
     * Gets the value of the studyBudget property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the studyBudget property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStudyBudget().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleTextType }
     * 
     * 
     */
    public List<SimpleTextType> getStudyBudget() {
        if (studyBudget == null) {
            studyBudget = new ArrayList<SimpleTextType>();
        }
        return this.studyBudget;
    }

    /**
     * Gets the value of the subject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubjectType }
     * 
     * 
     */
    public List<SubjectType> getSubject() {
        if (subject == null) {
            subject = new ArrayList<SubjectType>();
        }
        return this.subject;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the abstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbstractType }
     * 
     * 
     */
    public List<AbstractType> getAbstract() {
        if (_abstract == null) {
            _abstract = new ArrayList<AbstractType>();
        }
        return this._abstract;
    }

    /**
     * Gets the value of the sumDscr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sumDscr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSumDscr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SumDscrType }
     * 
     * 
     */
    public List<SumDscrType> getSumDscr() {
        if (sumDscr == null) {
            sumDscr = new ArrayList<SumDscrType>();
        }
        return this.sumDscr;
    }

    /**
     * Gets the value of the qualityStatement property.
     * 
     * @return
     *     possible object is
     *     {@link QualityStatementType }
     *     
     */
    public QualityStatementType getQualityStatement() {
        return qualityStatement;
    }

    /**
     * Sets the value of the qualityStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualityStatementType }
     *     
     */
    public void setQualityStatement(QualityStatementType value) {
        this.qualityStatement = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NotesType }
     * 
     * 
     */
    public List<NotesType> getNotes() {
        if (notes == null) {
            notes = new ArrayList<NotesType>();
        }
        return this.notes;
    }

    /**
     * Gets the value of the exPostEvaluation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exPostEvaluation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExPostEvaluation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExPostEvaluationType }
     * 
     * 
     */
    public List<ExPostEvaluationType> getExPostEvaluation() {
        if (exPostEvaluation == null) {
            exPostEvaluation = new ArrayList<ExPostEvaluationType>();
        }
        return this.exPostEvaluation;
    }

}
