//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 05:55:46 PM EDT 
//


package edu.umich.icpsr.ddi2.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for titlStmtType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="titlStmtType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:codebook:2_5}titl"/>
 *         &lt;element ref="{ddi:codebook:2_5}subTitl" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}altTitl" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}parTitl" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:codebook:2_5}IDNo" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "titlStmtType", namespace = "ddi:codebook:2_5", propOrder = {
    "titl",
    "subTitl",
    "altTitl",
    "parTitl",
    "idNo"
})
public class TitlStmtType
    extends BaseElementType
{

    @XmlElement(namespace = "ddi:codebook:2_5", required = true)
    protected SimpleTextType titl;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<SimpleTextType> subTitl;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<SimpleTextType> altTitl;
    @XmlElement(namespace = "ddi:codebook:2_5")
    protected List<SimpleTextType> parTitl;
    @XmlElement(name = "IDNo", namespace = "ddi:codebook:2_5")
    protected List<IDNoType> idNo;

    /**
     * Gets the value of the titl property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTextType }
     *     
     */
    public SimpleTextType getTitl() {
        return titl;
    }

    /**
     * Sets the value of the titl property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTextType }
     *     
     */
    public void setTitl(SimpleTextType value) {
        this.titl = value;
    }

    /**
     * Gets the value of the subTitl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subTitl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubTitl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleTextType }
     * 
     * 
     */
    public List<SimpleTextType> getSubTitl() {
        if (subTitl == null) {
            subTitl = new ArrayList<SimpleTextType>();
        }
        return this.subTitl;
    }

    /**
     * Gets the value of the altTitl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the altTitl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAltTitl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleTextType }
     * 
     * 
     */
    public List<SimpleTextType> getAltTitl() {
        if (altTitl == null) {
            altTitl = new ArrayList<SimpleTextType>();
        }
        return this.altTitl;
    }

    /**
     * Gets the value of the parTitl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parTitl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParTitl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleTextType }
     * 
     * 
     */
    public List<SimpleTextType> getParTitl() {
        if (parTitl == null) {
            parTitl = new ArrayList<SimpleTextType>();
        }
        return this.parTitl;
    }

    /**
     * Gets the value of the idNo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the idNo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIDNo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IDNoType }
     * 
     * 
     */
    public List<IDNoType> getIDNo() {
        if (idNo == null) {
            idNo = new ArrayList<IDNoType>();
        }
        return this.idNo;
    }

}
